import { textInput, textareaField, toggleField } from "../shared/form-helper.js";

export const meta = {
  id: "reflection",
  name: "Reflection",
  description: "Open-ended prompt with text response for learner reflection.",
  icon: "R",
  category: "Engagement",
  defaultConfig: {
    prompt: "Take a moment to reflect on what you learned.",
    placeholder: "Type your thoughts here...",
    autoGenerateDownload: false,
    maxLength: 2000,
  },
};

export function builder(root, config, onChange) {
  textareaField(root, "Prompt", config.prompt, (v) => onChange({ prompt: v }), 3);
  textInput(root, "Placeholder", config.placeholder, (v) => onChange({ placeholder: v }));
  toggleField(root, "Include in downloadable summary", config.autoGenerateDownload, (v) =>
    onChange({ autoGenerateDownload: v })
  );
}

export function viewer(root, config, host) {
  const wrap = document.createElement("div");
  wrap.style.cssText =
    "background:#fff;border:1px solid #e2e4ee;border-radius:14px;box-shadow:0 12px 32px rgba(28,30,38,.08);padding:24px;font-family:-apple-system,Segoe UI,Roboto,sans-serif;";

  const prompt = document.createElement("div");
  prompt.style.cssText = "font-size:17px;font-weight:650;color:#1c1e26;margin-bottom:16px;white-space:pre-wrap;";
  prompt.textContent = config.prompt;
  wrap.appendChild(prompt);

  const textarea = document.createElement("textarea");
  textarea.placeholder = config.placeholder;
  textarea.maxLength = config.maxLength;
  textarea.style.cssText =
    "width:100%;box-sizing:border-box;border:1px solid #c9cddd;border-radius:10px;padding:12px 14px;min-height:120px;resize:vertical;font:14px/1.6 -apple-system,Segoe UI,Roboto,sans-serif;color:#1c1e26;outline:none;transition:border-color .12s,box-shadow .12s;";
  textarea.addEventListener("focus", () => {
    textarea.style.borderColor = "#6d5df6";
    textarea.style.boxShadow = "0 0 0 4px rgba(109,93,246,.12)";
  });
  textarea.addEventListener("blur", () => {
    textarea.style.borderColor = "#c9cddd";
    textarea.style.boxShadow = "none";
  });

  const counter = document.createElement("div");
  counter.style.cssText =
    "text-align:right;font-size:12px;color:#8a8fa3;margin-top:6px;font-variant-numeric:tabular-nums;";
  const updateCounter = () => {
    counter.textContent = textarea.value.length + " / " + config.maxLength;
  };
  updateCounter();
  textarea.addEventListener("input", () => {
    updateCounter();
    if (host && host.track) {
      host.track("reflection.input", { length: textarea.value.length });
    }
  });
  wrap.appendChild(textarea);
  wrap.appendChild(counter);

  root.appendChild(wrap);

  const answer = { text: "" };
  textarea.addEventListener("input", () => {
    answer.text = textarea.value;
  });
  window.dispatchEvent(
    new CustomEvent("riseforge:reflection-answer", { detail: { config, answer } })
  );
}